<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SafeView.Domain\SafeView.Domain.csproj" />
    <ProjectReference Include="..\SafeView.Application\SafeView.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>
